matrix:
- name: Spellcheck markdown files
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  sources:
  - '_documentation-labs/**/*.md'
  default_encoding: utf-8