name: Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the main branch
  push:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  API_TOKEN: ${{ secrets.API_TOKEN }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
        bundler-cache: true

    - name: populate-graphql.rb script
      run: (cd _bash-scripts ; bundle exec ruby populate-graphql.rb)
      timeout-minutes: 3

    - name: "Build Site"
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production

    - name: "Deploy to AWS S3"
      run: aws s3 sync ./_site/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete --cache-control max-age=604800