# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Ruby
on:
  push:
    branches: [ workflow-test ]
  pull_request:
    branches: [ worfklow-test ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: head # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Test populate-graphql.rb script
        run: (cd _bash-scripts ; bundle exec ruby populate-graphql.rb)
      - name: Test for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with: 
          folder-path: _documentation-labs
      - name: Test jekyll doctor
        run: bundle exec jekyll doctor