# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ruby

on:
  push:
    branches: [ workflow-test ]
  pull_request:
    branches: [ worfklow-test ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: head
      - name: Install dependencies
        run: bundle install
      - run: cd _bash-scripts
      - run: ruby populate-graphql.rb --secret ${{ secrets.API_TOKEN }}
